name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: write
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install mkdocs
        run: pip install --upgrade pip && pip install mkdocs

      - name: Deploy docs
        working-directory: ${{ vars.GITHUB_WORKSPACE }}
        run: mkdocs gh-deploy