name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: write
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: ${{ vars.GITHUB_WORKSPACE }}/mkdocs.yaml
          EXTRA_PACKAGES: build-base